[build]
  command = "bash build.sh"
  functions = "functions"  # If you have serverless functions

[build.environment]
  PYTHON_VERSION = "3.8"

[[plugins]]
  package = "@netlify/plugin-functions-core"
